name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          port: 22
          script: |
            cd course-work
            git pull origin main
            docker-compose down
            docker-compose up -d --build

            echo "Waiting for the container to start..."
            until docker exec laravel_app ls >/dev/null 2>&1; do
              sleep 1
            done

            docker exec laravel_app php artisan migrate --force
            docker exec laravel_app npm run build
